site_name: 'Mezaque Silva'
docs_dir: 'docs'
site_url: 'https://guckesh.github.io'
nav:
  - Home: index.md
  - Projects:
      - Project 1: projects/dm1q.md
      - Project 2: projects/dm2q.md
      - Project 3: projects/dm3q.md

theme:
  name: material

repo_url: 'https://github.com/guckesh'
repo_name: 'Mezaque Silva GitHub'
